# @format

- name: variables from files
  hosts: localhost
  remote_user: root
  vars_files:
    - ./vars-store/vars.yml
  tasks:
    - name: print override information
      ansible.builtin.debug:
        msg: "Hi I am {{candidate}} age is: {{age}} role: {{role}}"
    - name: print inheretence information
      ansible.builtin.debug:
        msg: "Hi I am {{candidate}} age is: {{age}} role: {{role}}"
