# @format

- name: variables from inventory
  hosts: localhost
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "HI I am learning {{Course}} from {{Trainer}} with {{Duration}}"
