# @format

- name: variables preference
  hosts: local
  vars:
    WISHES: morning from play list
  vars_files:
    - vars.yml
  vars_prompt:
    - name: WISHES
      prompt: Please enter wishes from args
      private: false

  tasks:
    - name: get preference
      vars:
        WISHES: morning from tasks
      ansible.builtin.debug:
        msg: "Hi Jani, Good {{WISHES}}"
