# @format

- name: conditions
  hosts: local
  becomes: yes
  tasks:
    - name: check user exists or not
      ansible.builtin.command: id expense
      register: USER # show the error command
      ignore_errors: true
    
    - name: print User info
      ansible.builtin.debug: 
        msg: "print the command error info: {{USER}}"

    - name: creating User
      ansible.builtin.command: useradd expense 
      when: USER.rc != 0 # working like if conditions 

    - name: final line 
      ansible.builtin.debug:
        msg: "final command line"
        
