# @format

- name: default value
  hosts: local
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "Hi this the {{Course | default ('Ansible')}}"

    - name: print upper case
      vars:
        greeting: Good Morning
      ansible.builtin.debug:
        msg: "upper case: {{ greeting | upper }}"

    - name: print lower case
      vars:
        greeting: Good Morning
      ansible.builtin.debug:
        msg: "lower case: {{ greeting | lower }}"

    - name: Remove Deuplicates
      vars:
        list: [1, 2, 3, 3, 3, 4, 5, 5]
      ansible.builtin.debug:
        msg: "unique list: {{ list | unique }}"

    - name: print min and max age
      vars:
        ages: [20, 35, 27, 60]
      ansible.builtin.debug:
        msg: "min age: {{ ages | min }} max age: {{ages | max }}"

    - name: print dictonary to items
      vars:
        my_dict:
          Trainer: Siva Kumar
          Duration: 120 Hrs
          Course: DevOps with AWS
      ansible.builtin.debug:
        msg: "before conversion: {{my_dict}}"
      ansible.builtin.debug:
        msg: "After conversion: {{ my_dict | dict2items }}"

- name: print list to dictonary
  hosts: local
  vars:
    list: [
      {'key': 'Trainer', 'value': 'Siva Kumar'}, 
      {'key': 'Duration', 'value': '120 Hrs'}, 
      {'key': 'Course', 'value': 'DevOps with AWS'}
    ]
  tasks:
    - name: print list before dictonary 
      ansible.builtin.debug:
        msg: "dictonary: {{list}}"
    - name: print list After dictonary 
      ansible.builtin.debug:
        msg: "list: {{ list | items2dict }}"
    

